name: Build and push Docker image

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine image tags
        id: meta
        run: |
          # prefer git tag (vMAJOR.MINOR.PATCH) on the commit, else use short sha
          TAG=""
          if [ -n "${GITHUB_REF#refs/tags/}" ] && [[ "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
            if [[ $LATEST_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              TAG=$LATEST_TAG
            fi
          fi
          SHA=$(git rev-parse --short=12 HEAD)
          if [ -z "$TAG" ]; then
            TAG=sha-$SHA
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/kexamanager:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/kexamanager:sha-${{ steps.meta.outputs.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/kexamanager:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/kexamanager:cache,mode=max

      - name: Set latest tag if release tag
        if: startsWith(steps.meta.outputs.tag, 'v')
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/kexamanager:${{ steps.meta.outputs.tag }}
          docker tag ghcr.io/${{ github.repository_owner }}/kexamanager:${{ steps.meta.outputs.tag }} ghcr.io/${{ github.repository_owner }}/kexamanager:latest
          echo "Pushing latest tag"
          docker push ghcr.io/${{ github.repository_owner }}/kexamanager:latest
